name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [18.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} >> .env
          echo NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> .env
          echo NAVER_SECRET_KEY=${{ secrets.NAVER_SECRET_KEY }} >> .env
          echo NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }} >> .env
          echo NODEMAILER_USER=${{ secrets.NODEMAILER_USER }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo REFRESHTOKEN_EXPIRED=${{ secrets.REFRESHTOKEN_EXPIRED }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo TOKEN_EXPIRED=${{ secrets.TOKEN_EXPIRED }} >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build
