name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} >> .env
          echo NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> .env
          echo NAVER_SECRET_KEY=${{ secrets.NAVER_SECRET_KEY }} >> .env
          echo NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }} >> .env
          echo NODEMAILER_USER=${{ secrets.NODEMAILER_USER }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo REFRESHTOKEN_EXPIRED=${{ secrets.REFRESHTOKEN_EXPIRED }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo TOKEN_EXPIRED=${{ secrets.TOKEN_EXPIRED }} >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          npm install
          npm run build --if-present
    

          
###################################### 추가된 부분 ######################################

      - name: zip file
        run: zip -r hous.zip ./dist ./scripts ./appspec.yml ./.env ./package.json

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://hous-build/deploy/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name hous-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=hous-build,bundleType=zip,key=deploy/hous.zip
